# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-16 19:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('serialcode', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=255, null=True)),
                ('cost', models.IntegerField()),
            ],
            options={
                'db_table': 'hardware',
            },
        ),
        migrations.CreateModel(
            name='TrackHardware',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('repair_cost', models.IntegerField()),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('hardware', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='staff.Hardware')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'track_hardware',
            },
        ),
    ]
