# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-17 09:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepairHardware',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('repair_cost', models.IntegerField()),
            ],
            options={
                'db_table': 'rapair_hardware',
            },
        ),
        migrations.RemoveField(
            model_name='trackhardware',
            name='repair_cost',
        ),
        migrations.AlterField(
            model_name='trackhardware',
            name='start_date',
            field=models.DateField(default='2016-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repairhardware',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='staff.TrackHardware'),
        ),
    ]
