# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-17 10:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0002_auto_20170917_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardware',
            name='serialcode',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='trackhardware',
            unique_together=set([('user', 'hardware', 'start_date')]),
        ),
    ]
