# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-17 20:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_auto_20170917_1542'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='repairhardware',
            table='repair_hardware',
        ),
    ]
